; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lpc11u35]
platform = https://github.com/platformio/platform-nxplpc.git#e4590ca4c0a7ec4eb3854f5a6902ec98a7db71e6
board = lpc11u35
framework = mbed
platform_packages = 
	framework-mbed @ https://github.com/tai/mbed-os#support-lpc1114-on-pio
	toolchain-gccarmnoneeabi@1.70201.0
lib_deps = 
	mbed-king33jp/S6D0151@0.0.0+sha.18920a7a693e
	mbed-ajk/MODSERIAL@0.0.0+sha.ae0408ebdd68
	mbed-yasuyuki/EEPROM@0.0.0+sha.25e5bc71e65f
extra_scripts = post:add_checksum.py
